In [1]:
# MODULO 3.1 NUMPY PAIR PROGRMMING GGLORIA, LEYRE, VERONICA (24/7/24)
# 📝 NOTA En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos.

In [2]:
! pip install numpy

In [87]:
import numpy as np

In [4]:
# 1.1  Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. 
array2d = np.random.randint(34, 98,(4,3)) 
print(array2d)
# 1.2 Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.
array2d.shape # shape = ver la "forma" en este caso son filas y columnas
array2d.dtype # El tipo de datos que contiene: int, string...lo que sea

[[40 85 47]
 [56 63 70]
 [93 52 55]
 [67 47 46]]


dtype('int64')

In [5]:
# 2.Crea dos arrays (unidimensional, bidimensional) usando el método np.array().
# Las listas para crear los arrays son las siguientes

lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

np.array(lista1)
np.array(lista2)

array([[23, 45, 89, 56],
       [12, 43, 82, 44]])

In [6]:
# 3.1 Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:
lista3 = list(range(50)) 
array1d = np.array(lista3)

In [7]:
# 3.2 Extrae el primer elemento
array1d[0]

0

In [8]:
# 3.3 Los elementos que están en posición impar.
array1d[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [9]:
# 3.4 Los cuatro primeros elementos.
array1d[:4:]

array([0, 1, 2, 3])

In [10]:
# 3.5 Los últimos tres elementos.
array1d[-3::]

array([47, 48, 49])

In [11]:
# 3.6 Los elementos entre el 4 y el 8 (incluido).
array1d[4:8:]

array([4, 5, 6, 7])

In [36]:
# 4.1 Crea un array de dos dimensiones de 4 x 5 con el método que prefieras
array2d = np.random.randint(1,20,(4,5))
array2d

array([[14, 10, 17, 16, 16],
       [13,  1, 18,  3, 17],
       [ 2,  4, 17,  2, 11],
       [ 2,  8, 15,  6, 14]])

In [37]:
# 4.2 Extrae a primera fila y todas las columnas.
array2d[0]


array([14, 10, 17, 16, 16])

In [38]:
# 4.3 Todas las filas pares.
array2d[::2]

array([[14, 10, 17, 16, 16],
       [ 2,  4, 17,  2, 11]])

In [48]:
# 4.4 La primera columna y todas las filas.
array2d[:,0]

array([14, 13,  2,  2])

In [55]:
# 5.1 Crea un array bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y:
arraybidi = np.random.randint(0,51,(5,4))
arraybidi

array([[38, 19, 34, 41],
       [ 1, 26, 10, 36],
       [ 1,  6,  9, 10],
       [37, 38,  2, 44],
       [44, 32, 38, 19]])

In [64]:
# 5.2 Crea una mascara o filtro donde los valores mayores a 30
# y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".
array_mascara = np.where ((arraybidi > 30) | (arraybidi<10), "objetivo", "no es mi objetivo")

print (array_mascara)

[['objetivo' 'no es mi objetivo' 'objetivo' 'objetivo']
 ['objetivo' 'no es mi objetivo' 'no es mi objetivo' 'objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'no es mi objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'no es mi objetivo']]


In [65]:
# 5.3 Los valores de mi array bidimensional multiplicalos por el escalar 10.
#¿Escalar no es lo mismo que multiplicar directamente?
arraybidi * 10

array([[380, 190, 340, 410],
       [ 10, 260, 100, 360],
       [ 10,  60,  90, 100],
       [370, 380,  20, 440],
       [440, 320, 380, 190]])

In [66]:
# 6.1 Crea un nuevo array de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:
arraybidi2 = np.random.randint(0,51,(5,4))

In [67]:
# 6.2 Suma el primer array con el segundo.
arraybidi + arraybidi2

array([[39, 29, 49, 83],
       [26, 31, 59, 81],
       [ 5, 12, 11, 17],
       [50, 66, 28, 89],
       [59, 61, 41, 50]])

In [69]:
# 6.3 Aplicar la potencia para el primer array elevado al segundo.
arraybidi**arraybidi2


array([[                  38,        6131066257801, -5815062939426062336,
          569720415935503313],
       [                   1,             11881376,  -537617205517352960,
                           0],
       [                   1,                46656,                   81,
                    10000000],
       [ 3761551257857134389,   333500598735339520,             67108864,
                           0],
       [-2859305307937439744,                    0,                54872,
         2421078562627535771]])

In [70]:
# Función np power... ¿Por qué es mejor así que con 2 **?
np.power(arraybidi,arraybidi2)

array([[                  38,        6131066257801, -5815062939426062336,
          569720415935503313],
       [                   1,             11881376,  -537617205517352960,
                           0],
       [                   1,                46656,                   81,
                    10000000],
       [ 3761551257857134389,   333500598735339520,             67108864,
                           0],
       [-2859305307937439744,                    0,                54872,
         2421078562627535771]])

In [71]:
# 7.1 Crea un array, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100
array_max = np.random.randint(0,101,(10,10))
array_max

array([[ 98,  10,  94,  71,   5,  94,  93,  37,  74,  48],
       [ 28,  10,  52,  87,  59,  59,  73,  31,  57,  41],
       [ 23,  36,  26,  92,  81,   3,  42,  25,  51,  22],
       [ 37,  16,  36,  90,  57,  70,  45,  58,  22,  45],
       [ 57,  83,  21,   1,  43,   2,   8,  35,  85,  31],
       [ 73,   5,  73,  91,  43,  80,   7,  15,  67,  94],
       [ 32,  73,  75,  21,  31,  80,  62,  20,   1,  24],
       [ 99,   3,  40,  59,  89,  71,   8,  93,  30,  86],
       [ 40,  59,  37,  48,  71,  41,  90, 100,  37,  36],
       [ 72,  77,  68,  10,  92,  71,  31,  83,   3,  18]])

In [75]:
# 7.2 Calcula: La media de los elementos
np.mean(array_max,axis=1)

array([55.9, 37.2, 52.2, 57. , 57.1, 57.1, 45.9, 49.7, 42.7, 44.5])

In [85]:
# 7.3 La media de las columnas y redondéalo a dos decimales
media_columnas = np.mean(array_max,axis=0)
media_columnas


array([55.9, 37.2, 52.2, 57. , 57.1, 57.1, 45.9, 49.7, 42.7, 44.5])

In [94]:
# No sabemos por qué no nos sale
media_columnas_redondeo = np.round(media_columnas,2)
media_columnas_redondeo

array([55.9, 37.2, 52.2, 57. , 57.1, 57.1, 45.9, 49.7, 42.7, 44.5])

In [95]:
# 7.4 El valor máximo de cada fila
np.max(array_max, axis = 1)

array([ 98,  87,  92,  90,  85,  94,  80,  99, 100,  92])

In [97]:
# 7.5 El valor mínimo de cada fila
np.min(array_max, axis = 1)

array([ 5, 10,  3, 16,  1,  5,  1,  3, 36,  3])

In [98]:
# 7.6 Hay algun valor que sea mayor que 90 en tu array
array_max > 90

array([[ True, False,  True, False, False,  True,  True, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False]])

In [100]:
# 7.7 Donde los podemos encontrar, cuáles son sus índices
np.ndenumerate(array_max>90)


In [102]:
for index, value in np.ndenumerate(array_max>90):
    print(f"Índice: {index}, Valor: {value}")

Índice: (0, 0), Valor: True
Índice: (0, 1), Valor: False
Índice: (0, 2), Valor: True
Índice: (0, 3), Valor: False
Índice: (0, 4), Valor: False
Índice: (0, 5), Valor: True
Índice: (0, 6), Valor: True
Índice: (0, 7), Valor: False
Índice: (0, 8), Valor: False
Índice: (0, 9), Valor: False
Índice: (1, 0), Valor: False
Índice: (1, 1), Valor: False
Índice: (1, 2), Valor: False
Índice: (1, 3), Valor: False
Índice: (1, 4), Valor: False
Índice: (1, 5), Valor: False
Índice: (1, 6), Valor: False
Índice: (1, 7), Valor: False
Índice: (1, 8), Valor: False
Índice: (1, 9), Valor: False
Índice: (2, 0), Valor: False
Índice: (2, 1), Valor: False
Índice: (2, 2), Valor: False
Índice: (2, 3), Valor: True
Índice: (2, 4), Valor: False
Índice: (2, 5), Valor: False
Índice: (2, 6), Valor: False
Índice: (2, 7), Valor: False
Índice: (2, 8), Valor: False
Índice: (2, 9), Valor: False
Índice: (3, 0), Valor: False
Índice: (3, 1), Valor: False
Índice: (3, 2), Valor: False
Índice: (3, 3), Valor: False
Índice: (3, 4), Val

In [105]:
# 7.8 Ordena el array de mayor a menor
np.sort(-array_max)
# Ponemos otro menos pàra que nos lo devuelva en positivo
-np.sort(-array_max)

array([[ 98,  94,  94,  93,  74,  71,  48,  37,  10,   5],
       [ 87,  73,  59,  59,  57,  52,  41,  31,  28,  10],
       [ 92,  81,  51,  42,  36,  26,  25,  23,  22,   3],
       [ 90,  70,  58,  57,  45,  45,  37,  36,  22,  16],
       [ 85,  83,  57,  43,  35,  31,  21,   8,   2,   1],
       [ 94,  91,  80,  73,  73,  67,  43,  15,   7,   5],
       [ 80,  75,  73,  62,  32,  31,  24,  21,  20,   1],
       [ 99,  93,  89,  86,  71,  59,  40,  30,   8,   3],
       [100,  90,  71,  59,  48,  41,  40,  37,  37,  36],
       [ 92,  83,  77,  72,  71,  68,  31,  18,  10,   3]])