In [ ]:
# MODULO 3.1 NUMPY PAIR PROGRMMING GGLORIA, LEYRE, VERONICA (24/7/24)
# 📝 NOTA En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos.

In [1]:
! pip install numpy

In [2]:
import numpy as np

In [6]:
# 1.1  Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. 
array2d = np.random.randint(34, 98,(4,3)) 
print(array2d)
# 1.2 Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.
array2d.shape # shape = ver la "forma" en este caso son filas y columnas
array2d.dtype # El tipo de datos que contiene: int, string...lo que sea

[[97 43 35]
 [80 64 68]
 [78 83 78]
 [79 62 50]]


dtype('int64')

In [8]:
# 2.Crea dos arrays (unidimensional, bidimensional) usando el método np.array().
# Las listas para crear los arrays son las siguientes

lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

np.array(lista1)
np.array(lista2)

array([[23, 45, 89, 56],
       [12, 43, 82, 44]])

In [12]:
# 3.1 Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:
lista3 = list(range(50)) 
array1d = np.array(lista3)

In [13]:
# 3.2 Extrae el primer elemento
array1d[0]

0

In [22]:
# 3.3 Los elementos que están en posición impar.
array1d[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [25]:
# 3.4 Los cuatro primeros elementos.
array1d[:4:]

array([0, 1, 2, 3])

In [26]:
# 3.5 Los últimos tres elementos.
array1d[-3::]

array([47, 48, 49])

In [27]:
# 3.6 Los elementos entre el 4 y el 8 (incluido).
array1d[4:8:]

array([4, 5, 6, 7])

In [28]:
# 4.1 Crea un array de dos dimensiones de 4 x 5 con el método que prefieras
array2d = np.random.randint(1,20,(4,5))

In [ ]:
# 4.2 Extrae a primera fila y todas las columnas.

In [ ]:
# 4.3 Todas las filas pares.


In [ ]:
# 4.4 La primera columna y todas las filas.

In [ ]:
# 5.1 Crea un array bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y:


In [ ]:
# 5.2 Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".


In [ ]:
# 5.3 Los valores de mi array bidimensional multiplicalos por el escalar 10.

In [ ]:
# 6.1 Crea un nuevo array de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:


In [ ]:
# 6.2 Suma el primer array con el segundo.

In [ ]:
# 6.3 Aplicar la potencia para el primer array elevado al segundo.


In [ ]:
# 7.1 Crea un array, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100


In [ ]:
# 7.2 Calcula: La media de los elementos

In [ ]:
# 7.3 La media de las columnas y redondéalo a dos decimales


In [ ]:

# 7.4 El valor máximo de cada fila

In [ ]:
# 7.5 El valor mínimo de cada fila

In [ ]:
# 7.6 Hay algun valor que sea mayor que 90 en tu array

In [ ]:
# 7.7 Donde los podemos encontrar, cuáles son sus índices

In [ ]:
# 7.8 Ordena el array de mayor a menor